# Cloud Build configuration for CoverQuest - Updated with Cloud Functions
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '--build-arg', 'GEMINI_API_KEY=AIzaSyC3RGYIsyOGgx61hfdCZ2WWB50tDXH6WIw',
      '-t', 'gcr.io/$PROJECT_ID/coverquest', 
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/coverquest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'coverquest'
      - '--image'
      - 'gcr.io/$PROJECT_ID/coverquest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'functions'
      - 'deploy'
      - 'logGeneration'
      - '--runtime=nodejs20'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--region=us-central1'
      - '--source=functions/log-generation'
      - '--entry-point=logGeneration'
images:
  - 'gcr.io/$PROJECT_ID/coverquest'
options:
  logging: CLOUD_LOGGING_ONLY
