steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '--build-arg', 'GEMINI_API_KEY=$_GEMINI_API_KEY',
      '-t', 'gcr.io/$PROJECT_ID/coverquest', 
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/coverquest']
images:
  - 'gcr.io/$PROJECT_ID/coverquest'
options:
  logging: CLOUD_LOGGING_ONLY
