import React, { useState } from 'react';
import { galleryItems } from '../data/gallery';

export const GalleryView: React.FC = () => {
    const [flippedId, setFlippedId] = useState<number | null>(null);

    const handleCardClick = (id: number) => {
        setFlippedId(flippedId === id ? null : id);
    };

    return (
        <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-7xl mx-auto">
                <div className="text-center mb-12">
                    <h2 className="text-4xl font-serif font-bold text-gray-900 mb-4">Inspiration Gallery</h2>
                    <p className="text-lg text-gray-600 max-w-2xl mx-auto">
                        Explore 50 unique book cover designs generated by our AI. Click any cover to flip it and see the back design.
                    </p>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
                    {galleryItems.map((item) => (
                        <div
                            key={item.id}
                            className="relative group perspective-1000 h-[600px] cursor-pointer"
                            onClick={() => handleCardClick(item.id)}
                        >
                            <div className={`relative w-full h-full transition-all duration-700 transform-style-3d ${flippedId === item.id ? 'rotate-y-180' : ''}`}>

                                {/* Front Face */}
                                <div className="absolute inset-0 backface-hidden">
                                    <div className="h-full w-full rounded-lg shadow-xl overflow-hidden bg-gray-900 border border-gray-200 flex items-center justify-center">
                                        <img
                                            src={item.frontImage}
                                            alt={`Front cover for ${item.title}`}
                                            className="w-full h-full object-contain"
                                            loading="lazy"
                                        />
                                        <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent p-4 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <p className="text-white text-sm font-medium">Click to flip</p>
                                        </div>
                                    </div>
                                </div>

                                {/* Back Face */}
                                <div className="absolute inset-0 backface-hidden rotate-y-180">
                                    <div className="h-full w-full rounded-lg shadow-xl overflow-hidden bg-gray-900 border border-gray-200 flex items-center justify-center">
                                        <img
                                            src={item.backImage}
                                            alt={`Back cover for ${item.title}`}
                                            className="w-full h-full object-contain"
                                            loading="lazy"
                                        />
                                    </div>
                                </div>

                            </div>

                            <div className="mt-3 text-center">
                                <h3 className="text-sm font-semibold text-gray-900">{item.title}</h3>
                                <p className="text-xs text-gray-500">{item.genre}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};
